export const DEFAULT_DATA = [
  {
    leadSource: "Content Syndication",
    color: "#E8F4FD",
    accent: "#5BA4CF",
    details: ["Demand Science", "StackAdapt"],
  },
  {
    leadSource: "Event",
    color: "#E8FAF0",
    accent: "#4CAF82",
    details: ["Tradeshow", "Webinar"],
  },
  {
    leadSource: "Organic Search",
    color: "#FEF9E7",
    accent: "#D4AC0D",
    details: ["Google", "Bing", "Reddit"],
  },
  {
    leadSource: "Paid Search",
    color: "#FDF2FB",
    accent: "#C471B5",
    details: ["Google", "Bing"],
  },
  {
    leadSource: "Paid Social",
    color: "#EEF2FF",
    accent: "#6674CC",
    details: ["LinkedIn", "Facebook", "Instagram"],
  },
  {
    leadSource: "Prospecting",
    color: "#FFF3E8",
    accent: "#E8884A",
    details: ["BDR", "Sales*", "DemandZen", "Target Account"],
    note: "Lead Source Detail separates Marketing outbound (BDR, DemandZen) from Sales outbound (Sales). * = New value",
  },
  {
    leadSource: "Referral",
    color: "#F3EEF8",
    accent: "#9B6DC5",
    details: [
      "Partner",
      "Customer",
      "Word of Mouth",
      "Employee",
      "Executive: Marc Zionts",
      "Board of Directors",
      "SundaySky Board of Advisors",
    ],
  },
  {
    leadSource: "Social Media",
    color: "#FFF0F3",
    accent: "#E05C7A",
    details: ["LinkedIn", "Facebook", "Instagram", "Reddit", "Organic Posting"],
  },
  {
    leadSource: "Website - Direct",
    color: "#F0FAF0",
    accent: "#5BAD6F",
    details: ["Intent", "GTM Buddy"],
  },
  {
    leadSource: "Paid Meeting",
    color: "#FEF5E7",
    accent: "#E8A838",
    details: ["TBD"],
    note: "Detail values to be confirmed",
  },
  {
    leadSource: "Existing Customer",
    color: "#F5F0FA",
    accent: "#8B5FB8",
    details: ["Customer", "SSKY Player - Customer Example"],
  },
  {
    leadSource: "Partner",
    color: "#E8F0FE",
    accent: "#4A7FE8",
    details: [
      "Partner: Agency",
      "Partner: Allied Solutions",
      "Partner: Merkle",
      "Partner: Other",
    ],
  },
  {
    leadSource: "Email",
    color: "#F0FBF8",
    accent: "#3AAC8A",
    details: ["BDR", "Sales", "DemandZen"],
  },
  {
    leadSource: "Video",
    color: "#FFF0E8",
    accent: "#E87850",
    details: ["CTV - QR Code"],
  },
];

export const DEFAULT_RETIRED = [
  "RightBound",
  "LinkedIn Mining",
  "LinkedIn Sales Navigator",
  "Advisor: David Edelman",
  "Former Customer",
  "Customer: Unknown",
  "Prospecting (as detail)",
  "Prospecting - Other",
  "ZoomInfo",
];
